export const USERS = 'users'
export const RECIPES = 'recipes'
export const USER_RECIPES_RATINGS = 'user_recipes_ratings'
export const USER_RECIPES_FAVORITES = 'user_recipes_favorites'
export const AVERAGE_RECIPES_RATINGS = 'average_recipes_ratings'
